// import 'package:ai_chart_analysis/gen/svg/error_icon.gen.dart';
// import 'package:ai_chart_analysis/gen/svg/obsecure_off.gen.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:world_time/configs/configs.dart';
// import 'package:ai_chart_analysis/gen/svg/obsecure_on.gen.dart';

// part 'email.dart';
// part 'utils.dart';
// part 'password.dart';
part '_base.dart';
part '_data.dart';
part '_enums.dart';
part '_model.dart';
// part '_provider.dart';
// part '_validator.dart';
// part 'radio/radio.dart';
// part 'radio/_options.dart';
// part 'country_picker.dart';
// part 'first_name.dart';
// part 'last_name.dart';
// part 'details/country.dart';
// part 'details/gender.dart';
// part 'details/city.dart';
// part 'phone_input/phone_input.dart';
// part 'checkbox/checkbox.dart';
part 'text_input/content.dart';
part 'text_input/text_input.dart';
